"""add profile_exists to users table

Revision ID: f415b9335573
Revises: f24ac134dfb2
Create Date: 2025-02-14 19:38:13.831618

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f415b9335573"
down_revision: Union[str, None] = "f24ac134dfb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "profile_exists",
            sa.Boolean(),
            server_default="False",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "profile_exists")
    # ### end Alembic commands ###
