"""add email & register_as columns to profiles table

Revision ID: f24ac134dfb2
Revises: 1f349da4d369
Create Date: 2025-02-14 18:22:46.995502

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f24ac134dfb2"
down_revision: Union[str, None] = "1f349da4d369"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles", sa.Column("email", sa.String(length=150), nullable=False)
    )
    op.add_column(
        "profiles",
        sa.Column("register_as", sa.String(length=50), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "register_as")
    op.drop_column("profiles", "email")
    # ### end Alembic commands ###
