"""create user_offers_for_cleanings table

Revision ID: 927bb800d12f
Revises: f415b9335573
Create Date: 2025-02-14 21:04:00.831336

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "927bb800d12f"
down_revision: Union[str, None] = "f415b9335573"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_offers_for_cleanings",
        sa.Column("offerer_id", sa.UUID(), nullable=False),
        sa.Column("cleaning_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=120),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("requested_date", sa.Date(), nullable=True),
        sa.Column("requested_time", sa.Time(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cleaning_id"],
            ["cleanings.id"],
            name=op.f("fk_user_offers_for_cleanings_cleaning_id_cleanings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["offerer_id"],
            ["users.id"],
            name=op.f("fk_user_offers_for_cleanings_offerer_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "offerer_id",
            "cleaning_id",
            name=op.f("pk_user_offers_for_cleanings"),
        ),
    )
    op.create_index(
        op.f("ix_user_offers_for_cleanings_cleaning_id"),
        "user_offers_for_cleanings",
        ["cleaning_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_offers_for_cleanings_offerer_id"),
        "user_offers_for_cleanings",
        ["offerer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_offers_for_cleanings_status"),
        "user_offers_for_cleanings",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_offers_for_cleanings_status"),
        table_name="user_offers_for_cleanings",
    )
    op.drop_index(
        op.f("ix_user_offers_for_cleanings_offerer_id"),
        table_name="user_offers_for_cleanings",
    )
    op.drop_index(
        op.f("ix_user_offers_for_cleanings_cleaning_id"),
        table_name="user_offers_for_cleanings",
    )
    op.drop_table("user_offers_for_cleanings")
    # ### end Alembic commands ###
