"""create cleaner_evaluations table

Revision ID: b305bca66c4d
Revises: 927bb800d12f
Create Date: 2025-02-20 13:05:32.726324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b305bca66c4d"
down_revision: Union[str, None] = "927bb800d12f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cleaner_evaluations",
        sa.Column("owner", sa.UUID(), nullable=False),
        sa.Column("cleaner_id", sa.UUID(), nullable=False),
        sa.Column(
            "no_show", sa.Boolean(), server_default="False", nullable=False
        ),
        sa.Column("headline", sa.String(length=150), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("professionalism", sa.Integer(), nullable=True),
        sa.Column("completeness", sa.Integer(), nullable=True),
        sa.Column("efficiency", sa.Integer(), nullable=True),
        sa.Column("overall_rating", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cleaner_id"],
            ["users.id"],
            name=op.f("fk_cleaner_evaluations_cleaner_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cleaner_evaluations")),
        sa.UniqueConstraint(
            "owner",
            "cleaner_id",
            name=op.f("uq_cleaner_evaluations_owner_cleaner_id"),
        ),
    )
    op.create_index(
        op.f("ix_cleaner_evaluations_cleaner_id"),
        "cleaner_evaluations",
        ["cleaner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cleaner_evaluations_owner"),
        "cleaner_evaluations",
        ["owner"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_cleaner_evaluations_owner"), table_name="cleaner_evaluations"
    )
    op.drop_index(
        op.f("ix_cleaner_evaluations_cleaner_id"),
        table_name="cleaner_evaluations",
    )
    op.drop_table("cleaner_evaluations")
    # ### end Alembic commands ###
